function formatCurrency(value) {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  }).format(Number(value) || 0);
}

function getItemTotal(item) {
  const quantity = Number(item?.quantity) || 0;
  const unitPrice = Number(item?.unitPrice) || 0;
  const discount = Number(item?.discount) || 0;

  return Math.max(0, quantity * unitPrice - discount);
}

function getGrandTotal(items = []) {
  return items.reduce((total, item) => total + getItemTotal(item), 0);
}

function valueOrDash(value) {
  return value === undefined || value === null || value === "" ? "-" : value;
}

export default function SalesOrderPreview({ salesOrder, onBack, onConfirm }) {
  const isMarketplace = salesOrder?.orderType === "MARKETPLACE";

  const items = Array.isArray(salesOrder?.items) ? salesOrder.items : [];

  const grandTotal = getGrandTotal(items);

  const amountPaid = Number(salesOrder?.amountPaid) || 0;

  const balance = Math.max(0, grandTotal - amountPaid);

  return (
    <div className="sales-order-preview-overlay">
      <div className="sales-order-preview-modal">
        {/* HEADER */}

        <div className="sales-order-preview-header">
          <div>
            <h2>Review Sales Order</h2>

            <p>Check the information before creating the transaction.</p>
          </div>

          <button
            type="button"
            className="sales-order-preview-close"
            onClick={onBack}
            aria-label="Close preview">
            ×
          </button>
        </div>

        {/* CONTENT */}

        <div className="sales-order-preview-body">
          {/* ORDER INFORMATION */}

          <section className="sales-order-preview-section">
            <h3>Order Information</h3>

            <div className="sales-order-preview-grid">
              <div>
                <span>SO Number</span>

                <strong>
                  {valueOrDash(
                    salesOrder?.soNumber ||
                      salesOrder?.orderNumber ||
                      "Generated by system"
                  )}
                </strong>
              </div>

              <div>
                <span>Order Date</span>

                <strong>{valueOrDash(salesOrder?.orderDate)}</strong>
              </div>

              <div>
                <span>Deadline</span>

                <strong>{valueOrDash(salesOrder?.deadline)}</strong>
              </div>

              <div>
                <span>Priority</span>

                <strong>
                  {valueOrDash(salesOrder?.priority || "Regular")}
                </strong>
              </div>
            </div>
          </section>

          {/* CUSTOMER / MARKETPLACE */}

          {isMarketplace ? (
            <>
              <section className="sales-order-preview-section">
                <h3>Payment Information</h3>

                <div className="sales-order-preview-grid">
                  <div>
                    <span>Payment Status</span>

                    <strong className="preview-status-paid">PAID</strong>
                  </div>

                  <div>
                    <span>Payment Method</span>

                    <strong>Transfer</strong>
                  </div>

                  <div>
                    <span>Payment Type</span>

                    <strong>Automatic</strong>
                  </div>
                </div>
              </section>

              <section className="sales-order-preview-section">
                <h3>Marketplace Information</h3>

                <div className="sales-order-preview-grid">
                  <div>
                    <span>No. Resi</span>

                    <strong>{valueOrDash(salesOrder?.trackingNumber)}</strong>
                  </div>

                  <div>
                    <span>Customer</span>

                    <strong>
                      {valueOrDash(salesOrder?.marketplaceCustomer)}
                    </strong>
                  </div>

                  <div>
                    <span>Marketplace</span>

                    <strong>{valueOrDash(salesOrder?.marketplace)}</strong>
                  </div>
                </div>
              </section>
            </>
          ) : (
            <section className="sales-order-preview-section">
              <h3>Customer Information</h3>

              <div className="sales-order-preview-grid">
                <div>
                  <span>Customer</span>

                  <strong>{valueOrDash(salesOrder?.customer)}</strong>
                </div>

                <div>
                  <span>Mobile</span>

                  <strong>{valueOrDash(salesOrder?.mobile)}</strong>
                </div>

                <div>
                  <span>Email</span>

                  <strong>{valueOrDash(salesOrder?.email)}</strong>
                </div>

                <div className="preview-full-width">
                  <span>Address</span>

                  <strong>{valueOrDash(salesOrder?.address)}</strong>
                </div>
              </div>
            </section>
          )}

          {/* ORDER ITEMS */}

          <section className="sales-order-preview-section">
            <div className="sales-order-preview-section-title">
              <h3>Order Items</h3>

              <span>
                {items.length} item
                {items.length !== 1 ? "s" : ""}
              </span>
            </div>

            {items.length === 0 ? (
              <div className="sales-order-preview-empty">No order items.</div>
            ) : (
              <div className="sales-order-preview-items">
                {items.map((item, index) => (
                  <div
                    className="sales-order-preview-item"
                    key={item?.id || `preview-item-${index}`}>
                    <div className="sales-order-preview-item-main">
                      <strong>{valueOrDash(item?.product)}</strong>

                      <span>Qty: {valueOrDash(item?.quantity || 1)}</span>
                    </div>

                    <div className="sales-order-preview-item-values">
                      <span>
                        Unit Price
                        <strong>{formatCurrency(item?.unitPrice)}</strong>
                      </span>

                      <span>
                        Discount
                        <strong>{formatCurrency(item?.discount)}</strong>
                      </span>

                      <span>
                        Total
                        <strong>{formatCurrency(getItemTotal(item))}</strong>
                      </span>
                    </div>

                    {(item?.notes || item?.attachment) && (
                      <div className="sales-order-preview-item-extra">
                        {item?.notes && (
                          <div>
                            <span>Notes / Special Request</span>

                            <strong>{item.notes}</strong>
                          </div>
                        )}

                        {item?.attachment && (
                          <div>
                            <span>Attachment</span>

                            <strong>
                              {typeof item.attachment === "string"
                                ? item.attachment
                                : item.attachment.name || "Attached file"}
                            </strong>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </section>

          {/* DIRECT PAYMENT */}

          {!isMarketplace && (
            <section className="sales-order-preview-section">
              <h3>Payment</h3>

              <div className="sales-order-preview-grid">
                <div>
                  <span>Grand Total</span>

                  <strong>{formatCurrency(grandTotal)}</strong>
                </div>

                <div>
                  <span>Amount Paid</span>

                  <strong>{formatCurrency(amountPaid)}</strong>
                </div>

                <div>
                  <span>Balance</span>

                  <strong>{formatCurrency(balance)}</strong>
                </div>

                <div>
                  <span>Payment Method</span>

                  <strong>{valueOrDash(salesOrder?.paymentMethod)}</strong>
                </div>
              </div>
            </section>
          )}
        </div>

        {/* FOOTER */}

        <div className="sales-order-preview-footer">
          <button
            type="button"
            className="sales-order-secondary-button"
            onClick={onBack}>
            Back to Edit
          </button>

          <button
            type="button"
            className="ui-button-primary"
            onClick={onConfirm}>
            {isMarketplace ? "Create WO" : "Create Order"}
          </button>
        </div>
      </div>
    </div>
  );
}
